// Code generated by protoc-gen-go. DO NOT EDIT.
// source: examples/zap-marshaler/example.proto

package examples

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/kazegusuri/go-proto-zap-marshaler"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NumericEnum int32

const (
	NumericEnum_ZERO NumericEnum = 0
	NumericEnum_ONE  NumericEnum = 1
	NumericEnum_TWO  NumericEnum = 2
)

var NumericEnum_name = map[int32]string{
	0: "ZERO",
	1: "ONE",
	2: "TWO",
}

var NumericEnum_value = map[string]int32{
	"ZERO": 0,
	"ONE":  1,
	"TWO":  2,
}

func (x NumericEnum) String() string {
	return proto.EnumName(NumericEnum_name, int32(x))
}

func (NumericEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_722e198d308550d7, []int{0}
}

type AliasedEnum int32

const (
	AliasedEnum_UNKNOWN AliasedEnum = 0
	AliasedEnum_STARTED AliasedEnum = 1
	AliasedEnum_RUNNING AliasedEnum = 1
)

var AliasedEnum_name = map[int32]string{
	0: "UNKNOWN",
	1: "STARTED",
	// Duplicate value: 1: "RUNNING",
}

var AliasedEnum_value = map[string]int32{
	"UNKNOWN": 0,
	"STARTED": 1,
	"RUNNING": 1,
}

func (x AliasedEnum) String() string {
	return proto.EnumName(AliasedEnum_name, int32(x))
}

func (AliasedEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_722e198d308550d7, []int{1}
}

type EnumMessage_Nested int32

const (
	EnumMessage_UNKNOWN   EnumMessage_Nested = 0
	EnumMessage_PENDING   EnumMessage_Nested = 1
	EnumMessage_COMPLETED EnumMessage_Nested = 2
)

var EnumMessage_Nested_name = map[int32]string{
	0: "UNKNOWN",
	1: "PENDING",
	2: "COMPLETED",
}

var EnumMessage_Nested_value = map[string]int32{
	"UNKNOWN":   0,
	"PENDING":   1,
	"COMPLETED": 2,
}

func (x EnumMessage_Nested) String() string {
	return proto.EnumName(EnumMessage_Nested_name, int32(x))
}

func (EnumMessage_Nested) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_722e198d308550d7, []int{8, 0}
}

type NotLoggingEnumMessage_Nested int32

const (
	NotLoggingEnumMessage_UNKNOWN   NotLoggingEnumMessage_Nested = 0
	NotLoggingEnumMessage_PENDING   NotLoggingEnumMessage_Nested = 1
	NotLoggingEnumMessage_COMPLETED NotLoggingEnumMessage_Nested = 2
)

var NotLoggingEnumMessage_Nested_name = map[int32]string{
	0: "UNKNOWN",
	1: "PENDING",
	2: "COMPLETED",
}

var NotLoggingEnumMessage_Nested_value = map[string]int32{
	"UNKNOWN":   0,
	"PENDING":   1,
	"COMPLETED": 2,
}

func (x NotLoggingEnumMessage_Nested) String() string {
	return proto.EnumName(NotLoggingEnumMessage_Nested_name, int32(x))
}

func (NotLoggingEnumMessage_Nested) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_722e198d308550d7, []int{9, 0}
}

type SimpleMessage struct {
	StringValue          string   `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	BoolValue            bool     `protobuf:"varint,2,opt,name=bool_value,json=boolValue,proto3" json:"bool_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleMessage) Reset()         { *m = SimpleMessage{} }
func (m *SimpleMessage) String() string { return proto.CompactTextString(m) }
func (*SimpleMessage) ProtoMessage()    {}
func (*SimpleMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_722e198d308550d7, []int{0}
}

func (m *SimpleMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleMessage.Unmarshal(m, b)
}
func (m *SimpleMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleMessage.Marshal(b, m, deterministic)
}
func (m *SimpleMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleMessage.Merge(m, src)
}
func (m *SimpleMessage) XXX_Size() int {
	return xxx_messageInfo_SimpleMessage.Size(m)
}
func (m *SimpleMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleMessage proto.InternalMessageInfo

func (m *SimpleMessage) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

func (m *SimpleMessage) GetBoolValue() bool {
	if m != nil {
		return m.BoolValue
	}
	return false
}

type NotLoggingSimpleMessage struct {
	StringValue          string   `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	BoolValue            bool     `protobuf:"varint,2,opt,name=bool_value,json=boolValue,proto3" json:"bool_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotLoggingSimpleMessage) Reset()         { *m = NotLoggingSimpleMessage{} }
func (m *NotLoggingSimpleMessage) String() string { return proto.CompactTextString(m) }
func (*NotLoggingSimpleMessage) ProtoMessage()    {}
func (*NotLoggingSimpleMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_722e198d308550d7, []int{1}
}

func (m *NotLoggingSimpleMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotLoggingSimpleMessage.Unmarshal(m, b)
}
func (m *NotLoggingSimpleMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotLoggingSimpleMessage.Marshal(b, m, deterministic)
}
func (m *NotLoggingSimpleMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotLoggingSimpleMessage.Merge(m, src)
}
func (m *NotLoggingSimpleMessage) XXX_Size() int {
	return xxx_messageInfo_NotLoggingSimpleMessage.Size(m)
}
func (m *NotLoggingSimpleMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NotLoggingSimpleMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NotLoggingSimpleMessage proto.InternalMessageInfo

func (m *NotLoggingSimpleMessage) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

func (m *NotLoggingSimpleMessage) GetBoolValue() bool {
	if m != nil {
		return m.BoolValue
	}
	return false
}

type NumberMessage struct {
	FloatValue           float32  `protobuf:"fixed32,1,opt,name=float_value,json=floatValue,proto3" json:"float_value,omitempty"`
	DoubleValue          float64  `protobuf:"fixed64,2,opt,name=double_value,json=doubleValue,proto3" json:"double_value,omitempty"`
	Int32Value           int32    `protobuf:"varint,3,opt,name=int32_value,json=int32Value,proto3" json:"int32_value,omitempty"`
	Int64Value           int64    `protobuf:"varint,4,opt,name=int64_value,json=int64Value,proto3" json:"int64_value,omitempty"`
	Uint32Value          uint32   `protobuf:"varint,5,opt,name=uint32_value,json=uint32Value,proto3" json:"uint32_value,omitempty"`
	Uint64Value          uint64   `protobuf:"varint,6,opt,name=uint64_value,json=uint64Value,proto3" json:"uint64_value,omitempty"`
	Sint32Value          int32    `protobuf:"zigzag32,7,opt,name=sint32_value,json=sint32Value,proto3" json:"sint32_value,omitempty"`
	Sint64Value          int64    `protobuf:"zigzag64,8,opt,name=sint64_value,json=sint64Value,proto3" json:"sint64_value,omitempty"`
	Fixed32Value         uint32   `protobuf:"fixed32,9,opt,name=fixed32_value,json=fixed32Value,proto3" json:"fixed32_value,omitempty"`
	Fixed64Value         uint64   `protobuf:"fixed64,10,opt,name=fixed64_value,json=fixed64Value,proto3" json:"fixed64_value,omitempty"`
	Sfixed32Value        int32    `protobuf:"fixed32,11,opt,name=sfixed32_value,json=sfixed32Value,proto3" json:"sfixed32_value,omitempty"`
	Sfixed64Value        int64    `protobuf:"fixed64,12,opt,name=sfixed64_value,json=sfixed64Value,proto3" json:"sfixed64_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NumberMessage) Reset()         { *m = NumberMessage{} }
func (m *NumberMessage) String() string { return proto.CompactTextString(m) }
func (*NumberMessage) ProtoMessage()    {}
func (*NumberMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_722e198d308550d7, []int{2}
}

func (m *NumberMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NumberMessage.Unmarshal(m, b)
}
func (m *NumberMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NumberMessage.Marshal(b, m, deterministic)
}
func (m *NumberMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NumberMessage.Merge(m, src)
}
func (m *NumberMessage) XXX_Size() int {
	return xxx_messageInfo_NumberMessage.Size(m)
}
func (m *NumberMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NumberMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NumberMessage proto.InternalMessageInfo

func (m *NumberMessage) GetFloatValue() float32 {
	if m != nil {
		return m.FloatValue
	}
	return 0
}

func (m *NumberMessage) GetDoubleValue() float64 {
	if m != nil {
		return m.DoubleValue
	}
	return 0
}

func (m *NumberMessage) GetInt32Value() int32 {
	if m != nil {
		return m.Int32Value
	}
	return 0
}

func (m *NumberMessage) GetInt64Value() int64 {
	if m != nil {
		return m.Int64Value
	}
	return 0
}

func (m *NumberMessage) GetUint32Value() uint32 {
	if m != nil {
		return m.Uint32Value
	}
	return 0
}

func (m *NumberMessage) GetUint64Value() uint64 {
	if m != nil {
		return m.Uint64Value
	}
	return 0
}

func (m *NumberMessage) GetSint32Value() int32 {
	if m != nil {
		return m.Sint32Value
	}
	return 0
}

func (m *NumberMessage) GetSint64Value() int64 {
	if m != nil {
		return m.Sint64Value
	}
	return 0
}

func (m *NumberMessage) GetFixed32Value() uint32 {
	if m != nil {
		return m.Fixed32Value
	}
	return 0
}

func (m *NumberMessage) GetFixed64Value() uint64 {
	if m != nil {
		return m.Fixed64Value
	}
	return 0
}

func (m *NumberMessage) GetSfixed32Value() int32 {
	if m != nil {
		return m.Sfixed32Value
	}
	return 0
}

func (m *NumberMessage) GetSfixed64Value() int64 {
	if m != nil {
		return m.Sfixed64Value
	}
	return 0
}

type NotLoggingNumberMessage struct {
	FloatValue           float32  `protobuf:"fixed32,1,opt,name=float_value,json=floatValue,proto3" json:"float_value,omitempty"`
	DoubleValue          float64  `protobuf:"fixed64,2,opt,name=double_value,json=doubleValue,proto3" json:"double_value,omitempty"`
	Int32Value           int32    `protobuf:"varint,3,opt,name=int32_value,json=int32Value,proto3" json:"int32_value,omitempty"`
	Int64Value           int64    `protobuf:"varint,4,opt,name=int64_value,json=int64Value,proto3" json:"int64_value,omitempty"`
	Uint32Value          uint32   `protobuf:"varint,5,opt,name=uint32_value,json=uint32Value,proto3" json:"uint32_value,omitempty"`
	Uint64Value          uint64   `protobuf:"varint,6,opt,name=uint64_value,json=uint64Value,proto3" json:"uint64_value,omitempty"`
	Sint32Value          int32    `protobuf:"zigzag32,7,opt,name=sint32_value,json=sint32Value,proto3" json:"sint32_value,omitempty"`
	Sint64Value          int64    `protobuf:"zigzag64,8,opt,name=sint64_value,json=sint64Value,proto3" json:"sint64_value,omitempty"`
	Fixed32Value         uint32   `protobuf:"fixed32,9,opt,name=fixed32_value,json=fixed32Value,proto3" json:"fixed32_value,omitempty"`
	Fixed64Value         uint64   `protobuf:"fixed64,10,opt,name=fixed64_value,json=fixed64Value,proto3" json:"fixed64_value,omitempty"`
	Sfixed32Value        int32    `protobuf:"fixed32,11,opt,name=sfixed32_value,json=sfixed32Value,proto3" json:"sfixed32_value,omitempty"`
	Sfixed64Value        int64    `protobuf:"fixed64,12,opt,name=sfixed64_value,json=sfixed64Value,proto3" json:"sfixed64_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotLoggingNumberMessage) Reset()         { *m = NotLoggingNumberMessage{} }
func (m *NotLoggingNumberMessage) String() string { return proto.CompactTextString(m) }
func (*NotLoggingNumberMessage) ProtoMessage()    {}
func (*NotLoggingNumberMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_722e198d308550d7, []int{3}
}

func (m *NotLoggingNumberMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotLoggingNumberMessage.Unmarshal(m, b)
}
func (m *NotLoggingNumberMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotLoggingNumberMessage.Marshal(b, m, deterministic)
}
func (m *NotLoggingNumberMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotLoggingNumberMessage.Merge(m, src)
}
func (m *NotLoggingNumberMessage) XXX_Size() int {
	return xxx_messageInfo_NotLoggingNumberMessage.Size(m)
}
func (m *NotLoggingNumberMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NotLoggingNumberMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NotLoggingNumberMessage proto.InternalMessageInfo

func (m *NotLoggingNumberMessage) GetFloatValue() float32 {
	if m != nil {
		return m.FloatValue
	}
	return 0
}

func (m *NotLoggingNumberMessage) GetDoubleValue() float64 {
	if m != nil {
		return m.DoubleValue
	}
	return 0
}

func (m *NotLoggingNumberMessage) GetInt32Value() int32 {
	if m != nil {
		return m.Int32Value
	}
	return 0
}

func (m *NotLoggingNumberMessage) GetInt64Value() int64 {
	if m != nil {
		return m.Int64Value
	}
	return 0
}

func (m *NotLoggingNumberMessage) GetUint32Value() uint32 {
	if m != nil {
		return m.Uint32Value
	}
	return 0
}

func (m *NotLoggingNumberMessage) GetUint64Value() uint64 {
	if m != nil {
		return m.Uint64Value
	}
	return 0
}

func (m *NotLoggingNumberMessage) GetSint32Value() int32 {
	if m != nil {
		return m.Sint32Value
	}
	return 0
}

func (m *NotLoggingNumberMessage) GetSint64Value() int64 {
	if m != nil {
		return m.Sint64Value
	}
	return 0
}

func (m *NotLoggingNumberMessage) GetFixed32Value() uint32 {
	if m != nil {
		return m.Fixed32Value
	}
	return 0
}

func (m *NotLoggingNumberMessage) GetFixed64Value() uint64 {
	if m != nil {
		return m.Fixed64Value
	}
	return 0
}

func (m *NotLoggingNumberMessage) GetSfixed32Value() int32 {
	if m != nil {
		return m.Sfixed32Value
	}
	return 0
}

func (m *NotLoggingNumberMessage) GetSfixed64Value() int64 {
	if m != nil {
		return m.Sfixed64Value
	}
	return 0
}

type RepeatedNumberMessage struct {
	FloatValues          []float32 `protobuf:"fixed32,1,rep,packed,name=float_values,json=floatValues,proto3" json:"float_values,omitempty"`
	DoubleValues         []float64 `protobuf:"fixed64,2,rep,packed,name=double_values,json=doubleValues,proto3" json:"double_values,omitempty"`
	Int32Values          []int32   `protobuf:"varint,3,rep,packed,name=int32_values,json=int32Values,proto3" json:"int32_values,omitempty"`
	Int64Values          []int64   `protobuf:"varint,4,rep,packed,name=int64_values,json=int64Values,proto3" json:"int64_values,omitempty"`
	Uint32Values         []uint32  `protobuf:"varint,5,rep,packed,name=uint32_values,json=uint32Values,proto3" json:"uint32_values,omitempty"`
	Uint64Values         []uint64  `protobuf:"varint,6,rep,packed,name=uint64_values,json=uint64Values,proto3" json:"uint64_values,omitempty"`
	Sint32Values         []int32   `protobuf:"zigzag32,7,rep,packed,name=sint32_values,json=sint32Values,proto3" json:"sint32_values,omitempty"`
	Sint64Values         []int64   `protobuf:"zigzag64,8,rep,packed,name=sint64_values,json=sint64Values,proto3" json:"sint64_values,omitempty"`
	Fixed32Values        []uint32  `protobuf:"fixed32,9,rep,packed,name=fixed32_values,json=fixed32Values,proto3" json:"fixed32_values,omitempty"`
	Fixed64Values        []uint64  `protobuf:"fixed64,10,rep,packed,name=fixed64_values,json=fixed64Values,proto3" json:"fixed64_values,omitempty"`
	Sfixed32Values       []int32   `protobuf:"fixed32,11,rep,packed,name=sfixed32_values,json=sfixed32Values,proto3" json:"sfixed32_values,omitempty"`
	Sfixed64Values       []int64   `protobuf:"fixed64,12,rep,packed,name=sfixed64_values,json=sfixed64Values,proto3" json:"sfixed64_values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RepeatedNumberMessage) Reset()         { *m = RepeatedNumberMessage{} }
func (m *RepeatedNumberMessage) String() string { return proto.CompactTextString(m) }
func (*RepeatedNumberMessage) ProtoMessage()    {}
func (*RepeatedNumberMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_722e198d308550d7, []int{4}
}

func (m *RepeatedNumberMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepeatedNumberMessage.Unmarshal(m, b)
}
func (m *RepeatedNumberMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepeatedNumberMessage.Marshal(b, m, deterministic)
}
func (m *RepeatedNumberMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepeatedNumberMessage.Merge(m, src)
}
func (m *RepeatedNumberMessage) XXX_Size() int {
	return xxx_messageInfo_RepeatedNumberMessage.Size(m)
}
func (m *RepeatedNumberMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RepeatedNumberMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RepeatedNumberMessage proto.InternalMessageInfo

func (m *RepeatedNumberMessage) GetFloatValues() []float32 {
	if m != nil {
		return m.FloatValues
	}
	return nil
}

func (m *RepeatedNumberMessage) GetDoubleValues() []float64 {
	if m != nil {
		return m.DoubleValues
	}
	return nil
}

func (m *RepeatedNumberMessage) GetInt32Values() []int32 {
	if m != nil {
		return m.Int32Values
	}
	return nil
}

func (m *RepeatedNumberMessage) GetInt64Values() []int64 {
	if m != nil {
		return m.Int64Values
	}
	return nil
}

func (m *RepeatedNumberMessage) GetUint32Values() []uint32 {
	if m != nil {
		return m.Uint32Values
	}
	return nil
}

func (m *RepeatedNumberMessage) GetUint64Values() []uint64 {
	if m != nil {
		return m.Uint64Values
	}
	return nil
}

func (m *RepeatedNumberMessage) GetSint32Values() []int32 {
	if m != nil {
		return m.Sint32Values
	}
	return nil
}

func (m *RepeatedNumberMessage) GetSint64Values() []int64 {
	if m != nil {
		return m.Sint64Values
	}
	return nil
}

func (m *RepeatedNumberMessage) GetFixed32Values() []uint32 {
	if m != nil {
		return m.Fixed32Values
	}
	return nil
}

func (m *RepeatedNumberMessage) GetFixed64Values() []uint64 {
	if m != nil {
		return m.Fixed64Values
	}
	return nil
}

func (m *RepeatedNumberMessage) GetSfixed32Values() []int32 {
	if m != nil {
		return m.Sfixed32Values
	}
	return nil
}

func (m *RepeatedNumberMessage) GetSfixed64Values() []int64 {
	if m != nil {
		return m.Sfixed64Values
	}
	return nil
}

type NotLoggingRepeatedNumberMessage struct {
	FloatValues          []float32 `protobuf:"fixed32,1,rep,packed,name=float_values,json=floatValues,proto3" json:"float_values,omitempty"`
	DoubleValues         []float64 `protobuf:"fixed64,2,rep,packed,name=double_values,json=doubleValues,proto3" json:"double_values,omitempty"`
	Int32Values          []int32   `protobuf:"varint,3,rep,packed,name=int32_values,json=int32Values,proto3" json:"int32_values,omitempty"`
	Int64Values          []int64   `protobuf:"varint,4,rep,packed,name=int64_values,json=int64Values,proto3" json:"int64_values,omitempty"`
	Uint32Values         []uint32  `protobuf:"varint,5,rep,packed,name=uint32_values,json=uint32Values,proto3" json:"uint32_values,omitempty"`
	Uint64Values         []uint64  `protobuf:"varint,6,rep,packed,name=uint64_values,json=uint64Values,proto3" json:"uint64_values,omitempty"`
	Sint32Values         []int32   `protobuf:"zigzag32,7,rep,packed,name=sint32_values,json=sint32Values,proto3" json:"sint32_values,omitempty"`
	Sint64Values         []int64   `protobuf:"zigzag64,8,rep,packed,name=sint64_values,json=sint64Values,proto3" json:"sint64_values,omitempty"`
	Fixed32Values        []uint32  `protobuf:"fixed32,9,rep,packed,name=fixed32_values,json=fixed32Values,proto3" json:"fixed32_values,omitempty"`
	Fixed64Values        []uint64  `protobuf:"fixed64,10,rep,packed,name=fixed64_values,json=fixed64Values,proto3" json:"fixed64_values,omitempty"`
	Sfixed32Values       []int32   `protobuf:"fixed32,11,rep,packed,name=sfixed32_values,json=sfixed32Values,proto3" json:"sfixed32_values,omitempty"`
	Sfixed64Values       []int64   `protobuf:"fixed64,12,rep,packed,name=sfixed64_values,json=sfixed64Values,proto3" json:"sfixed64_values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *NotLoggingRepeatedNumberMessage) Reset()         { *m = NotLoggingRepeatedNumberMessage{} }
func (m *NotLoggingRepeatedNumberMessage) String() string { return proto.CompactTextString(m) }
func (*NotLoggingRepeatedNumberMessage) ProtoMessage()    {}
func (*NotLoggingRepeatedNumberMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_722e198d308550d7, []int{5}
}

func (m *NotLoggingRepeatedNumberMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotLoggingRepeatedNumberMessage.Unmarshal(m, b)
}
func (m *NotLoggingRepeatedNumberMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotLoggingRepeatedNumberMessage.Marshal(b, m, deterministic)
}
func (m *NotLoggingRepeatedNumberMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotLoggingRepeatedNumberMessage.Merge(m, src)
}
func (m *NotLoggingRepeatedNumberMessage) XXX_Size() int {
	return xxx_messageInfo_NotLoggingRepeatedNumberMessage.Size(m)
}
func (m *NotLoggingRepeatedNumberMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NotLoggingRepeatedNumberMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NotLoggingRepeatedNumberMessage proto.InternalMessageInfo

func (m *NotLoggingRepeatedNumberMessage) GetFloatValues() []float32 {
	if m != nil {
		return m.FloatValues
	}
	return nil
}

func (m *NotLoggingRepeatedNumberMessage) GetDoubleValues() []float64 {
	if m != nil {
		return m.DoubleValues
	}
	return nil
}

func (m *NotLoggingRepeatedNumberMessage) GetInt32Values() []int32 {
	if m != nil {
		return m.Int32Values
	}
	return nil
}

func (m *NotLoggingRepeatedNumberMessage) GetInt64Values() []int64 {
	if m != nil {
		return m.Int64Values
	}
	return nil
}

func (m *NotLoggingRepeatedNumberMessage) GetUint32Values() []uint32 {
	if m != nil {
		return m.Uint32Values
	}
	return nil
}

func (m *NotLoggingRepeatedNumberMessage) GetUint64Values() []uint64 {
	if m != nil {
		return m.Uint64Values
	}
	return nil
}

func (m *NotLoggingRepeatedNumberMessage) GetSint32Values() []int32 {
	if m != nil {
		return m.Sint32Values
	}
	return nil
}

func (m *NotLoggingRepeatedNumberMessage) GetSint64Values() []int64 {
	if m != nil {
		return m.Sint64Values
	}
	return nil
}

func (m *NotLoggingRepeatedNumberMessage) GetFixed32Values() []uint32 {
	if m != nil {
		return m.Fixed32Values
	}
	return nil
}

func (m *NotLoggingRepeatedNumberMessage) GetFixed64Values() []uint64 {
	if m != nil {
		return m.Fixed64Values
	}
	return nil
}

func (m *NotLoggingRepeatedNumberMessage) GetSfixed32Values() []int32 {
	if m != nil {
		return m.Sfixed32Values
	}
	return nil
}

func (m *NotLoggingRepeatedNumberMessage) GetSfixed64Values() []int64 {
	if m != nil {
		return m.Sfixed64Values
	}
	return nil
}

type NestedMessage struct {
	NestedValue          *NestedMessage_Nested   `protobuf:"bytes,1,opt,name=nested_value,json=nestedValue,proto3" json:"nested_value,omitempty"`
	RepeatedNestedValues []*NestedMessage_Nested `protobuf:"bytes,2,rep,name=repeated_nested_values,json=repeatedNestedValues,proto3" json:"repeated_nested_values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *NestedMessage) Reset()         { *m = NestedMessage{} }
func (m *NestedMessage) String() string { return proto.CompactTextString(m) }
func (*NestedMessage) ProtoMessage()    {}
func (*NestedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_722e198d308550d7, []int{6}
}

func (m *NestedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NestedMessage.Unmarshal(m, b)
}
func (m *NestedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NestedMessage.Marshal(b, m, deterministic)
}
func (m *NestedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NestedMessage.Merge(m, src)
}
func (m *NestedMessage) XXX_Size() int {
	return xxx_messageInfo_NestedMessage.Size(m)
}
func (m *NestedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NestedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NestedMessage proto.InternalMessageInfo

func (m *NestedMessage) GetNestedValue() *NestedMessage_Nested {
	if m != nil {
		return m.NestedValue
	}
	return nil
}

func (m *NestedMessage) GetRepeatedNestedValues() []*NestedMessage_Nested {
	if m != nil {
		return m.RepeatedNestedValues
	}
	return nil
}

type NestedMessage_Nested struct {
	Int32Value           int32    `protobuf:"varint,1,opt,name=int32_value,json=int32Value,proto3" json:"int32_value,omitempty"`
	StringValue          string   `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NestedMessage_Nested) Reset()         { *m = NestedMessage_Nested{} }
func (m *NestedMessage_Nested) String() string { return proto.CompactTextString(m) }
func (*NestedMessage_Nested) ProtoMessage()    {}
func (*NestedMessage_Nested) Descriptor() ([]byte, []int) {
	return fileDescriptor_722e198d308550d7, []int{6, 0}
}

func (m *NestedMessage_Nested) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NestedMessage_Nested.Unmarshal(m, b)
}
func (m *NestedMessage_Nested) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NestedMessage_Nested.Marshal(b, m, deterministic)
}
func (m *NestedMessage_Nested) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NestedMessage_Nested.Merge(m, src)
}
func (m *NestedMessage_Nested) XXX_Size() int {
	return xxx_messageInfo_NestedMessage_Nested.Size(m)
}
func (m *NestedMessage_Nested) XXX_DiscardUnknown() {
	xxx_messageInfo_NestedMessage_Nested.DiscardUnknown(m)
}

var xxx_messageInfo_NestedMessage_Nested proto.InternalMessageInfo

func (m *NestedMessage_Nested) GetInt32Value() int32 {
	if m != nil {
		return m.Int32Value
	}
	return 0
}

func (m *NestedMessage_Nested) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

type NotLoggingNestedMessage struct {
	NestedValue          *NotLoggingNestedMessage_Nested   `protobuf:"bytes,1,opt,name=nested_value,json=nestedValue,proto3" json:"nested_value,omitempty"`
	RepeatedNestedValues []*NotLoggingNestedMessage_Nested `protobuf:"bytes,2,rep,name=repeated_nested_values,json=repeatedNestedValues,proto3" json:"repeated_nested_values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *NotLoggingNestedMessage) Reset()         { *m = NotLoggingNestedMessage{} }
func (m *NotLoggingNestedMessage) String() string { return proto.CompactTextString(m) }
func (*NotLoggingNestedMessage) ProtoMessage()    {}
func (*NotLoggingNestedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_722e198d308550d7, []int{7}
}

func (m *NotLoggingNestedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotLoggingNestedMessage.Unmarshal(m, b)
}
func (m *NotLoggingNestedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotLoggingNestedMessage.Marshal(b, m, deterministic)
}
func (m *NotLoggingNestedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotLoggingNestedMessage.Merge(m, src)
}
func (m *NotLoggingNestedMessage) XXX_Size() int {
	return xxx_messageInfo_NotLoggingNestedMessage.Size(m)
}
func (m *NotLoggingNestedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NotLoggingNestedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NotLoggingNestedMessage proto.InternalMessageInfo

func (m *NotLoggingNestedMessage) GetNestedValue() *NotLoggingNestedMessage_Nested {
	if m != nil {
		return m.NestedValue
	}
	return nil
}

func (m *NotLoggingNestedMessage) GetRepeatedNestedValues() []*NotLoggingNestedMessage_Nested {
	if m != nil {
		return m.RepeatedNestedValues
	}
	return nil
}

type NotLoggingNestedMessage_Nested struct {
	Int32Value           int32    `protobuf:"varint,1,opt,name=int32_value,json=int32Value,proto3" json:"int32_value,omitempty"`
	StringValue          string   `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotLoggingNestedMessage_Nested) Reset()         { *m = NotLoggingNestedMessage_Nested{} }
func (m *NotLoggingNestedMessage_Nested) String() string { return proto.CompactTextString(m) }
func (*NotLoggingNestedMessage_Nested) ProtoMessage()    {}
func (*NotLoggingNestedMessage_Nested) Descriptor() ([]byte, []int) {
	return fileDescriptor_722e198d308550d7, []int{7, 0}
}

func (m *NotLoggingNestedMessage_Nested) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotLoggingNestedMessage_Nested.Unmarshal(m, b)
}
func (m *NotLoggingNestedMessage_Nested) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotLoggingNestedMessage_Nested.Marshal(b, m, deterministic)
}
func (m *NotLoggingNestedMessage_Nested) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotLoggingNestedMessage_Nested.Merge(m, src)
}
func (m *NotLoggingNestedMessage_Nested) XXX_Size() int {
	return xxx_messageInfo_NotLoggingNestedMessage_Nested.Size(m)
}
func (m *NotLoggingNestedMessage_Nested) XXX_DiscardUnknown() {
	xxx_messageInfo_NotLoggingNestedMessage_Nested.DiscardUnknown(m)
}

var xxx_messageInfo_NotLoggingNestedMessage_Nested proto.InternalMessageInfo

func (m *NotLoggingNestedMessage_Nested) GetInt32Value() int32 {
	if m != nil {
		return m.Int32Value
	}
	return 0
}

func (m *NotLoggingNestedMessage_Nested) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

type EnumMessage struct {
	NumericEnumValue          NumericEnum          `protobuf:"varint,1,opt,name=numeric_enum_value,json=numericEnumValue,proto3,enum=kazegusuri.zapmarshaler.example.NumericEnum" json:"numeric_enum_value,omitempty"`
	RepeatedNumericEnumValues []NumericEnum        `protobuf:"varint,2,rep,packed,name=repeated_numeric_enum_values,json=repeatedNumericEnumValues,proto3,enum=kazegusuri.zapmarshaler.example.NumericEnum" json:"repeated_numeric_enum_values,omitempty"`
	AliasedEnumValue          AliasedEnum          `protobuf:"varint,3,opt,name=aliased_enum_value,json=aliasedEnumValue,proto3,enum=kazegusuri.zapmarshaler.example.AliasedEnum" json:"aliased_enum_value,omitempty"`
	NestedEnumValue           EnumMessage_Nested   `protobuf:"varint,4,opt,name=nested_enum_value,json=nestedEnumValue,proto3,enum=kazegusuri.zapmarshaler.example.EnumMessage_Nested" json:"nested_enum_value,omitempty"`
	RepeatedNestedEnumValues  []EnumMessage_Nested `protobuf:"varint,5,rep,packed,name=repeated_nested_enum_values,json=repeatedNestedEnumValues,proto3,enum=kazegusuri.zapmarshaler.example.EnumMessage_Nested" json:"repeated_nested_enum_values,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}             `json:"-"`
	XXX_unrecognized          []byte               `json:"-"`
	XXX_sizecache             int32                `json:"-"`
}

func (m *EnumMessage) Reset()         { *m = EnumMessage{} }
func (m *EnumMessage) String() string { return proto.CompactTextString(m) }
func (*EnumMessage) ProtoMessage()    {}
func (*EnumMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_722e198d308550d7, []int{8}
}

func (m *EnumMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnumMessage.Unmarshal(m, b)
}
func (m *EnumMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnumMessage.Marshal(b, m, deterministic)
}
func (m *EnumMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnumMessage.Merge(m, src)
}
func (m *EnumMessage) XXX_Size() int {
	return xxx_messageInfo_EnumMessage.Size(m)
}
func (m *EnumMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EnumMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EnumMessage proto.InternalMessageInfo

func (m *EnumMessage) GetNumericEnumValue() NumericEnum {
	if m != nil {
		return m.NumericEnumValue
	}
	return NumericEnum_ZERO
}

func (m *EnumMessage) GetRepeatedNumericEnumValues() []NumericEnum {
	if m != nil {
		return m.RepeatedNumericEnumValues
	}
	return nil
}

func (m *EnumMessage) GetAliasedEnumValue() AliasedEnum {
	if m != nil {
		return m.AliasedEnumValue
	}
	return AliasedEnum_UNKNOWN
}

func (m *EnumMessage) GetNestedEnumValue() EnumMessage_Nested {
	if m != nil {
		return m.NestedEnumValue
	}
	return EnumMessage_UNKNOWN
}

func (m *EnumMessage) GetRepeatedNestedEnumValues() []EnumMessage_Nested {
	if m != nil {
		return m.RepeatedNestedEnumValues
	}
	return nil
}

type NotLoggingEnumMessage struct {
	NumericEnumValue          NumericEnum                    `protobuf:"varint,1,opt,name=numeric_enum_value,json=numericEnumValue,proto3,enum=kazegusuri.zapmarshaler.example.NumericEnum" json:"numeric_enum_value,omitempty"`
	RepeatedNumericEnumValues []NumericEnum                  `protobuf:"varint,2,rep,packed,name=repeated_numeric_enum_values,json=repeatedNumericEnumValues,proto3,enum=kazegusuri.zapmarshaler.example.NumericEnum" json:"repeated_numeric_enum_values,omitempty"`
	AliasedEnumValue          AliasedEnum                    `protobuf:"varint,3,opt,name=aliased_enum_value,json=aliasedEnumValue,proto3,enum=kazegusuri.zapmarshaler.example.AliasedEnum" json:"aliased_enum_value,omitempty"`
	NestedEnumValue           NotLoggingEnumMessage_Nested   `protobuf:"varint,4,opt,name=nested_enum_value,json=nestedEnumValue,proto3,enum=kazegusuri.zapmarshaler.example.NotLoggingEnumMessage_Nested" json:"nested_enum_value,omitempty"`
	RepeatedNestedEnumValues  []NotLoggingEnumMessage_Nested `protobuf:"varint,5,rep,packed,name=repeated_nested_enum_values,json=repeatedNestedEnumValues,proto3,enum=kazegusuri.zapmarshaler.example.NotLoggingEnumMessage_Nested" json:"repeated_nested_enum_values,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}                       `json:"-"`
	XXX_unrecognized          []byte                         `json:"-"`
	XXX_sizecache             int32                          `json:"-"`
}

func (m *NotLoggingEnumMessage) Reset()         { *m = NotLoggingEnumMessage{} }
func (m *NotLoggingEnumMessage) String() string { return proto.CompactTextString(m) }
func (*NotLoggingEnumMessage) ProtoMessage()    {}
func (*NotLoggingEnumMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_722e198d308550d7, []int{9}
}

func (m *NotLoggingEnumMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotLoggingEnumMessage.Unmarshal(m, b)
}
func (m *NotLoggingEnumMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotLoggingEnumMessage.Marshal(b, m, deterministic)
}
func (m *NotLoggingEnumMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotLoggingEnumMessage.Merge(m, src)
}
func (m *NotLoggingEnumMessage) XXX_Size() int {
	return xxx_messageInfo_NotLoggingEnumMessage.Size(m)
}
func (m *NotLoggingEnumMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NotLoggingEnumMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NotLoggingEnumMessage proto.InternalMessageInfo

func (m *NotLoggingEnumMessage) GetNumericEnumValue() NumericEnum {
	if m != nil {
		return m.NumericEnumValue
	}
	return NumericEnum_ZERO
}

func (m *NotLoggingEnumMessage) GetRepeatedNumericEnumValues() []NumericEnum {
	if m != nil {
		return m.RepeatedNumericEnumValues
	}
	return nil
}

func (m *NotLoggingEnumMessage) GetAliasedEnumValue() AliasedEnum {
	if m != nil {
		return m.AliasedEnumValue
	}
	return AliasedEnum_UNKNOWN
}

func (m *NotLoggingEnumMessage) GetNestedEnumValue() NotLoggingEnumMessage_Nested {
	if m != nil {
		return m.NestedEnumValue
	}
	return NotLoggingEnumMessage_UNKNOWN
}

func (m *NotLoggingEnumMessage) GetRepeatedNestedEnumValues() []NotLoggingEnumMessage_Nested {
	if m != nil {
		return m.RepeatedNestedEnumValues
	}
	return nil
}

type Oneof struct {
	// Types that are valid to be assigned to OneofValue:
	//	*Oneof_Int32Value
	//	*Oneof_StringValue
	OneofValue           isOneof_OneofValue `protobuf_oneof:"oneof_value"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Oneof) Reset()         { *m = Oneof{} }
func (m *Oneof) String() string { return proto.CompactTextString(m) }
func (*Oneof) ProtoMessage()    {}
func (*Oneof) Descriptor() ([]byte, []int) {
	return fileDescriptor_722e198d308550d7, []int{10}
}

func (m *Oneof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Oneof.Unmarshal(m, b)
}
func (m *Oneof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Oneof.Marshal(b, m, deterministic)
}
func (m *Oneof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Oneof.Merge(m, src)
}
func (m *Oneof) XXX_Size() int {
	return xxx_messageInfo_Oneof.Size(m)
}
func (m *Oneof) XXX_DiscardUnknown() {
	xxx_messageInfo_Oneof.DiscardUnknown(m)
}

var xxx_messageInfo_Oneof proto.InternalMessageInfo

type isOneof_OneofValue interface {
	isOneof_OneofValue()
}

type Oneof_Int32Value struct {
	Int32Value int32 `protobuf:"varint,1,opt,name=int32_value,json=int32Value,proto3,oneof"`
}

type Oneof_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3,oneof"`
}

func (*Oneof_Int32Value) isOneof_OneofValue() {}

func (*Oneof_StringValue) isOneof_OneofValue() {}

func (m *Oneof) GetOneofValue() isOneof_OneofValue {
	if m != nil {
		return m.OneofValue
	}
	return nil
}

func (m *Oneof) GetInt32Value() int32 {
	if x, ok := m.GetOneofValue().(*Oneof_Int32Value); ok {
		return x.Int32Value
	}
	return 0
}

func (m *Oneof) GetStringValue() string {
	if x, ok := m.GetOneofValue().(*Oneof_StringValue); ok {
		return x.StringValue
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Oneof) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Oneof_Int32Value)(nil),
		(*Oneof_StringValue)(nil),
	}
}

type OneofMessage struct {
	// Types that are valid to be assigned to OneofValue:
	//	*OneofMessage_Int32Value
	//	*OneofMessage_StringValue
	OneofValue           isOneofMessage_OneofValue `protobuf_oneof:"oneof_value"`
	RepeatedOneofValues  []*Oneof                  `protobuf:"bytes,3,rep,name=repeated_oneof_values,json=repeatedOneofValues,proto3" json:"repeated_oneof_values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *OneofMessage) Reset()         { *m = OneofMessage{} }
func (m *OneofMessage) String() string { return proto.CompactTextString(m) }
func (*OneofMessage) ProtoMessage()    {}
func (*OneofMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_722e198d308550d7, []int{11}
}

func (m *OneofMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OneofMessage.Unmarshal(m, b)
}
func (m *OneofMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OneofMessage.Marshal(b, m, deterministic)
}
func (m *OneofMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OneofMessage.Merge(m, src)
}
func (m *OneofMessage) XXX_Size() int {
	return xxx_messageInfo_OneofMessage.Size(m)
}
func (m *OneofMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_OneofMessage.DiscardUnknown(m)
}

var xxx_messageInfo_OneofMessage proto.InternalMessageInfo

type isOneofMessage_OneofValue interface {
	isOneofMessage_OneofValue()
}

type OneofMessage_Int32Value struct {
	Int32Value int32 `protobuf:"varint,1,opt,name=int32_value,json=int32Value,proto3,oneof"`
}

type OneofMessage_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3,oneof"`
}

func (*OneofMessage_Int32Value) isOneofMessage_OneofValue() {}

func (*OneofMessage_StringValue) isOneofMessage_OneofValue() {}

func (m *OneofMessage) GetOneofValue() isOneofMessage_OneofValue {
	if m != nil {
		return m.OneofValue
	}
	return nil
}

func (m *OneofMessage) GetInt32Value() int32 {
	if x, ok := m.GetOneofValue().(*OneofMessage_Int32Value); ok {
		return x.Int32Value
	}
	return 0
}

func (m *OneofMessage) GetStringValue() string {
	if x, ok := m.GetOneofValue().(*OneofMessage_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *OneofMessage) GetRepeatedOneofValues() []*Oneof {
	if m != nil {
		return m.RepeatedOneofValues
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*OneofMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*OneofMessage_Int32Value)(nil),
		(*OneofMessage_StringValue)(nil),
	}
}

type NotLoggingOneofMessage struct {
	// Types that are valid to be assigned to OneofValue:
	//	*NotLoggingOneofMessage_Int32Value
	//	*NotLoggingOneofMessage_StringValue
	OneofValue           isNotLoggingOneofMessage_OneofValue `protobuf_oneof:"oneof_value"`
	RepeatedOneofValues  []*Oneof                            `protobuf:"bytes,3,rep,name=repeated_oneof_values,json=repeatedOneofValues,proto3" json:"repeated_oneof_values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *NotLoggingOneofMessage) Reset()         { *m = NotLoggingOneofMessage{} }
func (m *NotLoggingOneofMessage) String() string { return proto.CompactTextString(m) }
func (*NotLoggingOneofMessage) ProtoMessage()    {}
func (*NotLoggingOneofMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_722e198d308550d7, []int{12}
}

func (m *NotLoggingOneofMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotLoggingOneofMessage.Unmarshal(m, b)
}
func (m *NotLoggingOneofMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotLoggingOneofMessage.Marshal(b, m, deterministic)
}
func (m *NotLoggingOneofMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotLoggingOneofMessage.Merge(m, src)
}
func (m *NotLoggingOneofMessage) XXX_Size() int {
	return xxx_messageInfo_NotLoggingOneofMessage.Size(m)
}
func (m *NotLoggingOneofMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NotLoggingOneofMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NotLoggingOneofMessage proto.InternalMessageInfo

type isNotLoggingOneofMessage_OneofValue interface {
	isNotLoggingOneofMessage_OneofValue()
}

type NotLoggingOneofMessage_Int32Value struct {
	Int32Value int32 `protobuf:"varint,1,opt,name=int32_value,json=int32Value,proto3,oneof"`
}

type NotLoggingOneofMessage_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3,oneof"`
}

func (*NotLoggingOneofMessage_Int32Value) isNotLoggingOneofMessage_OneofValue() {}

func (*NotLoggingOneofMessage_StringValue) isNotLoggingOneofMessage_OneofValue() {}

func (m *NotLoggingOneofMessage) GetOneofValue() isNotLoggingOneofMessage_OneofValue {
	if m != nil {
		return m.OneofValue
	}
	return nil
}

func (m *NotLoggingOneofMessage) GetInt32Value() int32 {
	if x, ok := m.GetOneofValue().(*NotLoggingOneofMessage_Int32Value); ok {
		return x.Int32Value
	}
	return 0
}

func (m *NotLoggingOneofMessage) GetStringValue() string {
	if x, ok := m.GetOneofValue().(*NotLoggingOneofMessage_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *NotLoggingOneofMessage) GetRepeatedOneofValues() []*Oneof {
	if m != nil {
		return m.RepeatedOneofValues
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*NotLoggingOneofMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*NotLoggingOneofMessage_Int32Value)(nil),
		(*NotLoggingOneofMessage_StringValue)(nil),
	}
}

type MapMessage struct {
	MappedValue          map[int32]string          `protobuf:"bytes,1,rep,name=mapped_value,json=mappedValue,proto3" json:"mapped_value,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	MappedEnumValue      map[string]NumericEnum    `protobuf:"bytes,2,rep,name=mapped_enum_value,json=mappedEnumValue,proto3" json:"mapped_enum_value,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3,enum=kazegusuri.zapmarshaler.example.NumericEnum"`
	MappedNestedValue    map[string]*NestedMessage `protobuf:"bytes,3,rep,name=mapped_nested_value,json=mappedNestedValue,proto3" json:"mapped_nested_value,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *MapMessage) Reset()         { *m = MapMessage{} }
func (m *MapMessage) String() string { return proto.CompactTextString(m) }
func (*MapMessage) ProtoMessage()    {}
func (*MapMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_722e198d308550d7, []int{13}
}

func (m *MapMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapMessage.Unmarshal(m, b)
}
func (m *MapMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapMessage.Marshal(b, m, deterministic)
}
func (m *MapMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapMessage.Merge(m, src)
}
func (m *MapMessage) XXX_Size() int {
	return xxx_messageInfo_MapMessage.Size(m)
}
func (m *MapMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_MapMessage.DiscardUnknown(m)
}

var xxx_messageInfo_MapMessage proto.InternalMessageInfo

func (m *MapMessage) GetMappedValue() map[int32]string {
	if m != nil {
		return m.MappedValue
	}
	return nil
}

func (m *MapMessage) GetMappedEnumValue() map[string]NumericEnum {
	if m != nil {
		return m.MappedEnumValue
	}
	return nil
}

func (m *MapMessage) GetMappedNestedValue() map[string]*NestedMessage {
	if m != nil {
		return m.MappedNestedValue
	}
	return nil
}

type NotLoggingMapMessage struct {
	MappedValue          map[int32]string          `protobuf:"bytes,1,rep,name=mapped_value,json=mappedValue,proto3" json:"mapped_value,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	MappedEnumValue      map[string]NumericEnum    `protobuf:"bytes,2,rep,name=mapped_enum_value,json=mappedEnumValue,proto3" json:"mapped_enum_value,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3,enum=kazegusuri.zapmarshaler.example.NumericEnum"`
	MappedNestedValue    map[string]*NestedMessage `protobuf:"bytes,3,rep,name=mapped_nested_value,json=mappedNestedValue,proto3" json:"mapped_nested_value,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *NotLoggingMapMessage) Reset()         { *m = NotLoggingMapMessage{} }
func (m *NotLoggingMapMessage) String() string { return proto.CompactTextString(m) }
func (*NotLoggingMapMessage) ProtoMessage()    {}
func (*NotLoggingMapMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_722e198d308550d7, []int{14}
}

func (m *NotLoggingMapMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotLoggingMapMessage.Unmarshal(m, b)
}
func (m *NotLoggingMapMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotLoggingMapMessage.Marshal(b, m, deterministic)
}
func (m *NotLoggingMapMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotLoggingMapMessage.Merge(m, src)
}
func (m *NotLoggingMapMessage) XXX_Size() int {
	return xxx_messageInfo_NotLoggingMapMessage.Size(m)
}
func (m *NotLoggingMapMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NotLoggingMapMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NotLoggingMapMessage proto.InternalMessageInfo

func (m *NotLoggingMapMessage) GetMappedValue() map[int32]string {
	if m != nil {
		return m.MappedValue
	}
	return nil
}

func (m *NotLoggingMapMessage) GetMappedEnumValue() map[string]NumericEnum {
	if m != nil {
		return m.MappedEnumValue
	}
	return nil
}

func (m *NotLoggingMapMessage) GetMappedNestedValue() map[string]*NestedMessage {
	if m != nil {
		return m.MappedNestedValue
	}
	return nil
}

type JsonNameOptionMessage struct {
	StringValue          string   `protobuf:"bytes,1,opt,name=string_value,json=renamed_value,proto3" json:"string_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JsonNameOptionMessage) Reset()         { *m = JsonNameOptionMessage{} }
func (m *JsonNameOptionMessage) String() string { return proto.CompactTextString(m) }
func (*JsonNameOptionMessage) ProtoMessage()    {}
func (*JsonNameOptionMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_722e198d308550d7, []int{15}
}

func (m *JsonNameOptionMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JsonNameOptionMessage.Unmarshal(m, b)
}
func (m *JsonNameOptionMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JsonNameOptionMessage.Marshal(b, m, deterministic)
}
func (m *JsonNameOptionMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JsonNameOptionMessage.Merge(m, src)
}
func (m *JsonNameOptionMessage) XXX_Size() int {
	return xxx_messageInfo_JsonNameOptionMessage.Size(m)
}
func (m *JsonNameOptionMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_JsonNameOptionMessage.DiscardUnknown(m)
}

var xxx_messageInfo_JsonNameOptionMessage proto.InternalMessageInfo

func (m *JsonNameOptionMessage) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

type NotLoggingJsonNameOptionMessage struct {
	StringValue          string   `protobuf:"bytes,1,opt,name=string_value,json=renamed_value,proto3" json:"string_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotLoggingJsonNameOptionMessage) Reset()         { *m = NotLoggingJsonNameOptionMessage{} }
func (m *NotLoggingJsonNameOptionMessage) String() string { return proto.CompactTextString(m) }
func (*NotLoggingJsonNameOptionMessage) ProtoMessage()    {}
func (*NotLoggingJsonNameOptionMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_722e198d308550d7, []int{16}
}

func (m *NotLoggingJsonNameOptionMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotLoggingJsonNameOptionMessage.Unmarshal(m, b)
}
func (m *NotLoggingJsonNameOptionMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotLoggingJsonNameOptionMessage.Marshal(b, m, deterministic)
}
func (m *NotLoggingJsonNameOptionMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotLoggingJsonNameOptionMessage.Merge(m, src)
}
func (m *NotLoggingJsonNameOptionMessage) XXX_Size() int {
	return xxx_messageInfo_NotLoggingJsonNameOptionMessage.Size(m)
}
func (m *NotLoggingJsonNameOptionMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NotLoggingJsonNameOptionMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NotLoggingJsonNameOptionMessage proto.InternalMessageInfo

func (m *NotLoggingJsonNameOptionMessage) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

type WellKnownTypeMessage struct {
	Duration             *duration.Duration   `protobuf:"bytes,1,opt,name=duration,proto3" json:"duration,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *WellKnownTypeMessage) Reset()         { *m = WellKnownTypeMessage{} }
func (m *WellKnownTypeMessage) String() string { return proto.CompactTextString(m) }
func (*WellKnownTypeMessage) ProtoMessage()    {}
func (*WellKnownTypeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_722e198d308550d7, []int{17}
}

func (m *WellKnownTypeMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WellKnownTypeMessage.Unmarshal(m, b)
}
func (m *WellKnownTypeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WellKnownTypeMessage.Marshal(b, m, deterministic)
}
func (m *WellKnownTypeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WellKnownTypeMessage.Merge(m, src)
}
func (m *WellKnownTypeMessage) XXX_Size() int {
	return xxx_messageInfo_WellKnownTypeMessage.Size(m)
}
func (m *WellKnownTypeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_WellKnownTypeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_WellKnownTypeMessage proto.InternalMessageInfo

func (m *WellKnownTypeMessage) GetDuration() *duration.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

func (m *WellKnownTypeMessage) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type NotLoggingWellKnownTypeMessage struct {
	Duration             *duration.Duration   `protobuf:"bytes,1,opt,name=duration,proto3" json:"duration,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *NotLoggingWellKnownTypeMessage) Reset()         { *m = NotLoggingWellKnownTypeMessage{} }
func (m *NotLoggingWellKnownTypeMessage) String() string { return proto.CompactTextString(m) }
func (*NotLoggingWellKnownTypeMessage) ProtoMessage()    {}
func (*NotLoggingWellKnownTypeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_722e198d308550d7, []int{18}
}

func (m *NotLoggingWellKnownTypeMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotLoggingWellKnownTypeMessage.Unmarshal(m, b)
}
func (m *NotLoggingWellKnownTypeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotLoggingWellKnownTypeMessage.Marshal(b, m, deterministic)
}
func (m *NotLoggingWellKnownTypeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotLoggingWellKnownTypeMessage.Merge(m, src)
}
func (m *NotLoggingWellKnownTypeMessage) XXX_Size() int {
	return xxx_messageInfo_NotLoggingWellKnownTypeMessage.Size(m)
}
func (m *NotLoggingWellKnownTypeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NotLoggingWellKnownTypeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NotLoggingWellKnownTypeMessage proto.InternalMessageInfo

func (m *NotLoggingWellKnownTypeMessage) GetDuration() *duration.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

func (m *NotLoggingWellKnownTypeMessage) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type MixedLoggingMessage struct {
	StringValue          string   `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	BoolValue            bool     `protobuf:"varint,2,opt,name=bool_value,json=boolValue,proto3" json:"bool_value,omitempty"`
	Int32Value           int32    `protobuf:"varint,3,opt,name=int32_value,json=int32Value,proto3" json:"int32_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MixedLoggingMessage) Reset()         { *m = MixedLoggingMessage{} }
func (m *MixedLoggingMessage) String() string { return proto.CompactTextString(m) }
func (*MixedLoggingMessage) ProtoMessage()    {}
func (*MixedLoggingMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_722e198d308550d7, []int{19}
}

func (m *MixedLoggingMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MixedLoggingMessage.Unmarshal(m, b)
}
func (m *MixedLoggingMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MixedLoggingMessage.Marshal(b, m, deterministic)
}
func (m *MixedLoggingMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MixedLoggingMessage.Merge(m, src)
}
func (m *MixedLoggingMessage) XXX_Size() int {
	return xxx_messageInfo_MixedLoggingMessage.Size(m)
}
func (m *MixedLoggingMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_MixedLoggingMessage.DiscardUnknown(m)
}

var xxx_messageInfo_MixedLoggingMessage proto.InternalMessageInfo

func (m *MixedLoggingMessage) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

func (m *MixedLoggingMessage) GetBoolValue() bool {
	if m != nil {
		return m.BoolValue
	}
	return false
}

func (m *MixedLoggingMessage) GetInt32Value() int32 {
	if m != nil {
		return m.Int32Value
	}
	return 0
}

func init() {
	proto.RegisterEnum("kazegusuri.zapmarshaler.example.NumericEnum", NumericEnum_name, NumericEnum_value)
	proto.RegisterEnum("kazegusuri.zapmarshaler.example.AliasedEnum", AliasedEnum_name, AliasedEnum_value)
	proto.RegisterEnum("kazegusuri.zapmarshaler.example.EnumMessage_Nested", EnumMessage_Nested_name, EnumMessage_Nested_value)
	proto.RegisterEnum("kazegusuri.zapmarshaler.example.NotLoggingEnumMessage_Nested", NotLoggingEnumMessage_Nested_name, NotLoggingEnumMessage_Nested_value)
	proto.RegisterType((*SimpleMessage)(nil), "kazegusuri.zapmarshaler.example.SimpleMessage")
	proto.RegisterType((*NotLoggingSimpleMessage)(nil), "kazegusuri.zapmarshaler.example.NotLoggingSimpleMessage")
	proto.RegisterType((*NumberMessage)(nil), "kazegusuri.zapmarshaler.example.NumberMessage")
	proto.RegisterType((*NotLoggingNumberMessage)(nil), "kazegusuri.zapmarshaler.example.NotLoggingNumberMessage")
	proto.RegisterType((*RepeatedNumberMessage)(nil), "kazegusuri.zapmarshaler.example.RepeatedNumberMessage")
	proto.RegisterType((*NotLoggingRepeatedNumberMessage)(nil), "kazegusuri.zapmarshaler.example.NotLoggingRepeatedNumberMessage")
	proto.RegisterType((*NestedMessage)(nil), "kazegusuri.zapmarshaler.example.NestedMessage")
	proto.RegisterType((*NestedMessage_Nested)(nil), "kazegusuri.zapmarshaler.example.NestedMessage.Nested")
	proto.RegisterType((*NotLoggingNestedMessage)(nil), "kazegusuri.zapmarshaler.example.NotLoggingNestedMessage")
	proto.RegisterType((*NotLoggingNestedMessage_Nested)(nil), "kazegusuri.zapmarshaler.example.NotLoggingNestedMessage.Nested")
	proto.RegisterType((*EnumMessage)(nil), "kazegusuri.zapmarshaler.example.EnumMessage")
	proto.RegisterType((*NotLoggingEnumMessage)(nil), "kazegusuri.zapmarshaler.example.NotLoggingEnumMessage")
	proto.RegisterType((*Oneof)(nil), "kazegusuri.zapmarshaler.example.Oneof")
	proto.RegisterType((*OneofMessage)(nil), "kazegusuri.zapmarshaler.example.OneofMessage")
	proto.RegisterType((*NotLoggingOneofMessage)(nil), "kazegusuri.zapmarshaler.example.NotLoggingOneofMessage")
	proto.RegisterType((*MapMessage)(nil), "kazegusuri.zapmarshaler.example.MapMessage")
	proto.RegisterMapType((map[string]NumericEnum)(nil), "kazegusuri.zapmarshaler.example.MapMessage.MappedEnumValueEntry")
	proto.RegisterMapType((map[string]*NestedMessage)(nil), "kazegusuri.zapmarshaler.example.MapMessage.MappedNestedValueEntry")
	proto.RegisterMapType((map[int32]string)(nil), "kazegusuri.zapmarshaler.example.MapMessage.MappedValueEntry")
	proto.RegisterType((*NotLoggingMapMessage)(nil), "kazegusuri.zapmarshaler.example.NotLoggingMapMessage")
	proto.RegisterMapType((map[string]NumericEnum)(nil), "kazegusuri.zapmarshaler.example.NotLoggingMapMessage.MappedEnumValueEntry")
	proto.RegisterMapType((map[string]*NestedMessage)(nil), "kazegusuri.zapmarshaler.example.NotLoggingMapMessage.MappedNestedValueEntry")
	proto.RegisterMapType((map[int32]string)(nil), "kazegusuri.zapmarshaler.example.NotLoggingMapMessage.MappedValueEntry")
	proto.RegisterType((*JsonNameOptionMessage)(nil), "kazegusuri.zapmarshaler.example.JsonNameOptionMessage")
	proto.RegisterType((*NotLoggingJsonNameOptionMessage)(nil), "kazegusuri.zapmarshaler.example.NotLoggingJsonNameOptionMessage")
	proto.RegisterType((*WellKnownTypeMessage)(nil), "kazegusuri.zapmarshaler.example.WellKnownTypeMessage")
	proto.RegisterType((*NotLoggingWellKnownTypeMessage)(nil), "kazegusuri.zapmarshaler.example.NotLoggingWellKnownTypeMessage")
	proto.RegisterType((*MixedLoggingMessage)(nil), "kazegusuri.zapmarshaler.example.MixedLoggingMessage")
}

func init() {
	proto.RegisterFile("examples/zap-marshaler/example.proto", fileDescriptor_722e198d308550d7)
}

var fileDescriptor_722e198d308550d7 = []byte{
	// 1569 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x59, 0x5d, 0x73, 0xdb, 0xd4,
	0x16, 0x8d, 0x2c, 0x3b, 0xb1, 0xb7, 0xe4, 0xc4, 0x55, 0x92, 0x5e, 0xd7, 0xf7, 0xde, 0x5a, 0xb6,
	0x6f, 0x6e, 0x9c, 0x96, 0x3a, 0x43, 0xfa, 0x31, 0x1d, 0x86, 0x42, 0x1b, 0xe2, 0x52, 0xda, 0xc4,
	0xee, 0xa4, 0x29, 0x9d, 0x09, 0xcc, 0x04, 0x19, 0x2b, 0x46, 0x53, 0xeb, 0x63, 0x7c, 0xa4, 0xd2,
	0x66, 0xfa, 0xcc, 0x2b, 0xc3, 0x13, 0xc3, 0x13, 0xbf, 0x83, 0xd7, 0xc2, 0x53, 0xf9, 0x05, 0xf0,
	0x0a, 0x3f, 0x84, 0xd1, 0xe7, 0xd9, 0x47, 0x3e, 0x89, 0xeb, 0x26, 0xbc, 0xf1, 0x16, 0xe9, 0x6c,
	0xad, 0x75, 0xf6, 0x5e, 0x6b, 0x1f, 0xef, 0x48, 0xf0, 0x3f, 0xfd, 0xb9, 0x66, 0x3a, 0x43, 0x9d,
	0xac, 0x1f, 0x69, 0xce, 0x15, 0x53, 0x1b, 0x91, 0xaf, 0xb4, 0xa1, 0x3e, 0x5a, 0x8f, 0x6e, 0xb7,
	0x9c, 0x91, 0xed, 0xda, 0x4a, 0xf5, 0xa9, 0x76, 0xa4, 0x0f, 0x3c, 0xe2, 0x8d, 0x8c, 0xd6, 0x91,
	0xe6, 0x24, 0x61, 0xad, 0x28, 0xac, 0xb2, 0x78, 0xa4, 0x39, 0x07, 0xf4, 0x76, 0xf0, 0x54, 0xe5,
	0xe2, 0xc0, 0xb6, 0x07, 0x43, 0x7d, 0x3d, 0xb8, 0xea, 0x79, 0x87, 0xeb, 0x7d, 0x6f, 0xa4, 0xb9,
	0x86, 0x6d, 0x45, 0xeb, 0xd5, 0xf4, 0xba, 0x6b, 0x98, 0x3a, 0x71, 0x35, 0xd3, 0x09, 0x03, 0xea,
	0x1a, 0x14, 0x1f, 0x19, 0x3e, 0xfe, 0x8e, 0x4e, 0x88, 0x36, 0xd0, 0x95, 0x35, 0x90, 0x89, 0x3b,
	0x32, 0xac, 0xc1, 0xc1, 0x33, 0x6d, 0xe8, 0xe9, 0x65, 0x41, 0x15, 0x9a, 0x85, 0xcd, 0xd9, 0xd7,
	0xaf, 0xaa, 0x99, 0xbc, 0xb0, 0x2b, 0x85, 0x6b, 0x9f, 0xfa, 0x4b, 0xca, 0x0a, 0x40, 0xcf, 0xb6,
	0x87, 0x51, 0x60, 0x46, 0x15, 0x9a, 0xf9, 0x24, 0xb0, 0xe0, 0xaf, 0x04, 0x61, 0xf5, 0xcf, 0xe0,
	0x5f, 0x1d, 0xdb, 0xdd, 0xb6, 0x07, 0x03, 0xc3, 0x1a, 0xb0, 0x64, 0x35, 0x1e, 0x19, 0x4b, 0xf2,
	0xdf, 0x71, 0x12, 0x0c, 0xfe, 0x43, 0x16, 0x8a, 0x1d, 0xcf, 0xec, 0xe9, 0xa3, 0x18, 0x73, 0x15,
	0xa4, 0xc3, 0xa1, 0xad, 0xb9, 0x08, 0x32, 0x93, 0x6c, 0x0b, 0x82, 0xa5, 0x10, 0x79, 0x0d, 0xe4,
	0xbe, 0xed, 0xf5, 0x86, 0x3a, 0xc2, 0x16, 0x68, 0xa6, 0xe1, 0x5a, 0x18, 0xba, 0x0a, 0x92, 0x61,
	0xb9, 0x57, 0x37, 0xa2, 0x48, 0x51, 0x15, 0x9a, 0x39, 0x8a, 0x19, 0x2c, 0xe1, 0xc0, 0x1b, 0xd7,
	0xa2, 0xc0, 0xac, 0x2a, 0x34, 0x45, 0x26, 0xf0, 0xc6, 0xb5, 0x84, 0xdc, 0xc3, 0x90, 0x39, 0x55,
	0x68, 0x16, 0x29, 0xb9, 0x87, 0x30, 0xa3, 0xd0, 0x04, 0x74, 0x56, 0x15, 0x9a, 0x59, 0x36, 0x14,
	0xa1, 0x12, 0x8c, 0x3a, 0xa7, 0x0a, 0xcd, 0x73, 0x48, 0x3c, 0x16, 0x95, 0x60, 0xd4, 0xbc, 0x2a,
	0x34, 0x15, 0x36, 0x34, 0x46, 0xbd, 0x0c, 0xc5, 0x43, 0xe3, 0xb9, 0xde, 0x4f, 0x60, 0x0b, 0xaa,
	0xd0, 0x9c, 0x4b, 0x62, 0xe5, 0x68, 0x91, 0x0d, 0x4e, 0x80, 0x41, 0x15, 0x9a, 0xb3, 0xa9, 0xe0,
	0x18, 0xf9, 0x0a, 0xcc, 0x13, 0x16, 0x5a, 0x52, 0x85, 0xe6, 0x42, 0x12, 0x5d, 0x24, 0x0c, 0x76,
	0x12, 0x9e, 0x80, 0xcb, 0xaa, 0xd0, 0x2c, 0xa5, 0xc3, 0x23, 0xf4, 0xfa, 0xcf, 0x22, 0x76, 0x1e,
	0xeb, 0x92, 0x2a, 0xc7, 0x25, 0x8c, 0x3b, 0x6a, 0x3c, 0x77, 0xb0, 0xae, 0xa8, 0x72, 0x5c, 0xc1,
	0xb8, 0xa1, 0xca, 0x71, 0x03, 0xe3, 0x82, 0x1a, 0xcf, 0x05, 0xac, 0xfa, 0x35, 0x9e, 0xfa, 0xac,
	0xea, 0x35, 0x9e, 0xea, 0xac, 0xda, 0x35, 0x9e, 0xda, 0xac, 0xca, 0x0d, 0xae, 0xca, 0x29, 0x75,
	0x1b, 0x5c, 0x75, 0x53, 0xaa, 0xae, 0xf0, 0x55, 0x4d, 0xab, 0xb9, 0xc2, 0x57, 0x33, 0xad, 0xe2,
	0x4f, 0x59, 0x58, 0xde, 0xd5, 0x1d, 0x5d, 0x73, 0xf5, 0x3e, 0xab, 0xe1, 0x1a, 0xc8, 0x48, 0x43,
	0x52, 0x16, 0x54, 0x11, 0xb5, 0xba, 0x44, 0xc5, 0x24, 0xbe, 0x2b, 0xb1, 0x9a, 0xa4, 0x9c, 0x51,
	0x45, 0xd4, 0xec, 0x32, 0x92, 0x95, 0xf8, 0xb8, 0xa8, 0x9c, 0xa4, 0x2c, 0xaa, 0x22, 0x6a, 0x77,
	0x89, 0x96, 0x35, 0x0e, 0x8d, 0x13, 0x20, 0xe5, 0xac, 0x2a, 0xa2, 0x86, 0x97, 0x68, 0x79, 0x83,
	0x2d, 0x78, 0x0c, 0x6c, 0x4e, 0x15, 0x51, 0xcb, 0xcb, 0x1e, 0xc6, 0x8d, 0x82, 0x29, 0xf0, 0xac,
	0x2a, 0xa2, 0xa6, 0x97, 0xbd, 0x14, 0x32, 0x61, 0x90, 0xe7, 0x54, 0x11, 0xb5, 0xbd, 0x4c, 0x52,
	0xc8, 0x84, 0x41, 0xce, 0xab, 0x22, 0x6a, 0x7c, 0x99, 0x60, 0xe4, 0x2b, 0x30, 0xcf, 0x08, 0x49,
	0xca, 0x05, 0x55, 0x44, 0xad, 0x5f, 0xc4, 0x82, 0xd2, 0x70, 0x0a, 0x0e, 0xaa, 0x88, 0x9a, 0xbf,
	0x88, 0x85, 0x25, 0xca, 0x3a, 0x2c, 0x90, 0x14, 0xbc, 0xa4, 0x8a, 0xa8, 0xfd, 0xe7, 0x09, 0x8b,
	0x9f, 0x3c, 0x40, 0x09, 0x64, 0x55, 0x44, 0x07, 0xc0, 0x3c, 0x63, 0x1d, 0x52, 0xff, 0x43, 0x84,
	0x2a, 0x3d, 0x01, 0xf8, 0x2e, 0xaa, 0xf1, 0x5c, 0xc4, 0xba, 0xa7, 0xc1, 0x75, 0x4f, 0xca, 0x35,
	0x35, 0x9e, 0x6b, 0x58, 0xb7, 0xd4, 0x78, 0x6e, 0x61, 0x5d, 0xd2, 0xe0, 0xba, 0x24, 0xe5, 0x8e,
	0x06, 0xd7, 0x1d, 0x29, 0x57, 0x34, 0xb8, 0xae, 0x48, 0xb9, 0xa1, 0xc1, 0x75, 0x43, 0xca, 0x05,
	0x2b, 0x7c, 0x17, 0xa4, 0xd5, 0x5f, 0xe1, 0xab, 0x9f, 0x56, 0x7d, 0xf5, 0x18, 0xd5, 0xc7, 0xd4,
	0x5e, 0x3d, 0x46, 0xed, 0x31, 0x95, 0x7f, 0xc9, 0x40, 0xb1, 0xa3, 0x13, 0x57, 0xef, 0xc7, 0x9a,
	0x7e, 0x01, 0xb2, 0x15, 0xdc, 0x40, 0xc7, 0xbb, 0xb4, 0x71, 0xbd, 0x35, 0x61, 0xc6, 0x6a, 0x31,
	0x28, 0xd1, 0x15, 0xed, 0xe6, 0x10, 0x32, 0x3c, 0xbc, 0x08, 0x9c, 0x1f, 0x45, 0x76, 0x3a, 0xc0,
	0x54, 0xa1, 0x37, 0x4e, 0xcd, 0xb5, 0x14, 0x83, 0x77, 0x28, 0x27, 0xa9, 0x7c, 0x0e, 0xb3, 0xe1,
	0x75, 0x7a, 0x20, 0x11, 0x8e, 0x1d, 0x48, 0xd2, 0xe3, 0x5c, 0xe6, 0xd8, 0x71, 0xae, 0xfe, 0x2a,
	0xc3, 0xfc, 0x5c, 0x32, 0x05, 0xed, 0x71, 0x0b, 0xfa, 0xe1, 0xe4, 0x24, 0xf9, 0x78, 0x51, 0xba,
	0x6c, 0x49, 0xbd, 0x09, 0x25, 0x3d, 0x35, 0x1b, 0xbf, 0xa8, 0xdb, 0x49, 0x51, 0xab, 0x9c, 0xa2,
	0x32, 0xc5, 0xac, 0xf1, 0x8a, 0xc9, 0x16, 0xf1, 0xcf, 0x2c, 0x48, 0x6d, 0xcb, 0x33, 0x69, 0xe1,
	0x14, 0xcb, 0x33, 0xf5, 0x91, 0xf1, 0xe5, 0x81, 0x6e, 0x79, 0x26, 0x82, 0x9e, 0xdf, 0x78, 0x67,
	0x72, 0x42, 0xe1, 0xa3, 0x3e, 0x60, 0xa2, 0x59, 0xc9, 0xa2, 0x37, 0xe3, 0xc2, 0xfd, 0x87, 0x16,
	0x6e, 0x8c, 0x2c, 0x2c, 0xdf, 0xdb, 0xb2, 0x5d, 0x18, 0xd1, 0x43, 0x93, 0x61, 0x25, 0x7e, 0x6a,
	0xda, 0xd0, 0xd0, 0x88, 0xde, 0xc7, 0xa9, 0x89, 0x6f, 0x98, 0xda, 0x9d, 0xf0, 0x51, 0x36, 0x35,
	0x8d, 0xde, 0x0c, 0x53, 0x1b, 0xc0, 0xb9, 0xc8, 0x0a, 0x88, 0x22, 0x1b, 0x50, 0x5c, 0x9d, 0x48,
	0x81, 0x74, 0x48, 0xf7, 0xd7, 0x42, 0x88, 0x4a, 0x89, 0x8e, 0xe0, 0xdf, 0x69, 0xf3, 0xe1, 0x12,
	0xe6, 0x82, 0x12, 0x9e, 0x8a, 0xb2, 0xcc, 0xba, 0x8f, 0x16, 0xb2, 0xfe, 0x6e, 0xe2, 0x40, 0x09,
	0xe6, 0x1e, 0x77, 0x1e, 0x74, 0xba, 0x4f, 0x3a, 0xa5, 0x19, 0xff, 0xe2, 0x61, 0xbb, 0xb3, 0xf5,
	0x49, 0xe7, 0xe3, 0x92, 0xa0, 0x14, 0xa1, 0xf0, 0x51, 0x77, 0xe7, 0xe1, 0x76, 0x7b, 0xaf, 0xbd,
	0x55, 0xca, 0xd4, 0x7f, 0xcf, 0xc2, 0x32, 0x75, 0x3b, 0x36, 0xdc, 0xfe, 0x59, 0x19, 0x8e, 0x63,
	0x34, 0xf3, 0xec, 0x8d, 0x76, 0x92, 0xc1, 0xf6, 0xcf, 0xca, 0x60, 0x1c, 0x63, 0x19, 0xc7, 0x1b,
	0xeb, 0xd6, 0x14, 0xe7, 0xcc, 0xb8, 0xde, 0xe3, 0xd6, 0x7a, 0xf9, 0x26, 0xd6, 0x3a, 0x25, 0xe9,
	0x99, 0x9a, 0xcb, 0x82, 0x5c, 0xd7, 0xd2, 0xed, 0x43, 0x65, 0xed, 0x84, 0x5f, 0x99, 0x7b, 0x33,
	0xcc, 0xd1, 0x78, 0xf9, 0xa4, 0xdf, 0x99, 0x7b, 0x33, 0xcc, 0x21, 0xb9, 0x59, 0x04, 0xc9, 0xf6,
	0x09, 0xc2, 0xd8, 0xfa, 0x6f, 0x02, 0xc8, 0x01, 0x21, 0x1d, 0xec, 0xff, 0x16, 0x5e, 0xa5, 0x07,
	0xcb, 0x89, 0x12, 0x68, 0x03, 0xe1, 0xac, 0x26, 0x6d, 0xfc, 0x7f, 0xa2, 0x06, 0xc1, 0x2e, 0x93,
	0x8e, 0x5e, 0x8c, 0xc1, 0x82, 0xdb, 0x61, 0xbd, 0xd3, 0xb9, 0xfd, 0x2a, 0xc0, 0x79, 0xaa, 0x1c,
	0x93, 0x65, 0x8d, 0x93, 0x65, 0x2a, 0xbb, 0x06, 0x2f, 0xbb, 0x74, 0x56, 0xfb, 0x67, 0x92, 0xd5,
	0x1b, 0x65, 0xf3, 0x6d, 0x0e, 0x60, 0x47, 0x73, 0xe2, 0x0c, 0x06, 0x20, 0x9b, 0x9a, 0xe3, 0xa0,
	0xa9, 0xc0, 0x27, 0x7c, 0x7f, 0x22, 0x21, 0x85, 0xf0, 0xff, 0x74, 0xa2, 0x9f, 0xe2, 0xb6, 0xe5,
	0x8e, 0x5e, 0xd0, 0xd1, 0xc4, 0xa4, 0x2b, 0x8a, 0x0b, 0xe7, 0x22, 0x22, 0xd4, 0xad, 0xe1, 0x54,
	0x70, 0x7b, 0x7a, 0xb6, 0xa4, 0x3b, 0x58, 0xc6, 0x05, 0x93, 0x5d, 0x55, 0x8e, 0x60, 0x31, 0x62,
	0x65, 0x66, 0x9f, 0xb0, 0xac, 0x9b, 0xd3, 0xf3, 0xa2, 0xb1, 0x83, 0x65, 0x8e, 0x92, 0x43, 0xeb,
	0x95, 0x0f, 0xa0, 0x94, 0x2e, 0x8d, 0x52, 0x02, 0xf1, 0xa9, 0xfe, 0x22, 0x9a, 0x4b, 0xfc, 0x3f,
	0x95, 0x25, 0xc8, 0xe1, 0x49, 0x24, 0xbc, 0x78, 0x2f, 0x73, 0x53, 0xa8, 0x38, 0xb0, 0xc4, 0x4b,
	0x16, 0x63, 0x14, 0x42, 0x8c, 0x4d, 0x8c, 0x31, 0xed, 0xe9, 0x8d, 0x18, 0x5d, 0x38, 0xcf, 0x4f,
	0x93, 0xc3, 0xb9, 0x85, 0x39, 0xa5, 0x8d, 0xd6, 0x74, 0xc3, 0x32, 0x62, 0xad, 0xff, 0x98, 0x83,
	0x25, 0xda, 0x5f, 0xc8, 0x9b, 0x06, 0xd7, 0x9b, 0x77, 0xa7, 0x38, 0x66, 0x4f, 0x70, 0x29, 0xeb,
	0xce, 0x67, 0xc7, 0xbb, 0xf3, 0xfe, 0x69, 0xf8, 0x58, 0xe9, 0xc6, 0xfd, 0xf9, 0xf2, 0x24, 0x7f,
	0x6e, 0x9f, 0x86, 0x39, 0x2d, 0xe1, 0x3f, 0x0e, 0x7d, 0x7b, 0x87, 0x6e, 0xc1, 0xf2, 0x7d, 0x62,
	0x5b, 0x1d, 0xcd, 0xd4, 0xbb, 0x8e, 0x6b, 0xd8, 0x56, 0xec, 0xd0, 0xcb, 0x27, 0xbe, 0x69, 0x2f,
	0x8e, 0x74, 0x4b, 0x33, 0x63, 0x51, 0xeb, 0x77, 0xf1, 0x8b, 0x0c, 0x3e, 0x5e, 0x83, 0xfb, 0x32,
	0x3d, 0x85, 0xf3, 0xbd, 0x00, 0x4b, 0x4f, 0xf4, 0xe1, 0xf0, 0x81, 0x65, 0x7f, 0x6d, 0xed, 0xbd,
	0x70, 0x92, 0x57, 0xf1, 0xb7, 0x20, 0x1f, 0x7f, 0x3b, 0x88, 0xfe, 0xbb, 0xbb, 0xd0, 0x0a, 0x3f,
	0x1e, 0xb4, 0xe2, 0x8f, 0x07, 0xad, 0xad, 0x28, 0x20, 0xd9, 0x64, 0xf2, 0x88, 0x72, 0x1b, 0x0a,
	0xc9, 0xa7, 0x85, 0xa8, 0x66, 0x95, 0xb1, 0xe7, 0xf7, 0xe2, 0x08, 0xfa, 0x99, 0x20, 0x79, 0xa8,
	0xfe, 0x9d, 0x00, 0x17, 0x69, 0x8a, 0xdc, 0x3d, 0x5e, 0x9f, 0x62, 0x8f, 0x68, 0x6f, 0x37, 0xa7,
	0xda, 0x1b, 0xde, 0xd3, 0x37, 0x02, 0x2c, 0xee, 0x18, 0xcf, 0xf5, 0x7e, 0xdc, 0x28, 0xd3, 0x7f,
	0x24, 0x69, 0x70, 0x3e, 0x92, 0x64, 0x5f, 0xbf, 0xaa, 0xce, 0xa0, 0xaf, 0x18, 0x13, 0xdf, 0x24,
	0x5f, 0x5a, 0x03, 0x09, 0x99, 0x5a, 0xc9, 0x43, 0x76, 0xbf, 0xbd, 0xdb, 0x2d, 0xcd, 0x28, 0x73,
	0x20, 0x76, 0x3b, 0xed, 0x92, 0xe0, 0xff, 0xb1, 0xf7, 0xa4, 0x5b, 0xca, 0x5c, 0xba, 0x09, 0x12,
	0x1a, 0x7d, 0xc7, 0xa6, 0xbe, 0x47, 0x7b, 0x77, 0x76, 0xfd, 0x31, 0x4f, 0xf0, 0x2f, 0x76, 0x1f,
	0x77, 0x3a, 0xc1, 0x08, 0x58, 0xc9, 0x94, 0x84, 0x4d, 0xd8, 0xcf, 0xc7, 0x9f, 0xaa, 0x7a, 0xb3,
	0x41, 0x61, 0xae, 0xfe, 0x15, 0x00, 0x00, 0xff, 0xff, 0x06, 0x8e, 0x0d, 0x56, 0xbd, 0x1a, 0x00,
	0x00,
}
