// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: examples/example.proto

/*
Package examples is a generated protocol buffer package.

It is generated from these files:
	examples/example.proto

It has these top-level messages:
	SimpleMessage
	NumberMessage
	RepeatedNumberMessage
	NestedMessage
	EnumMessage
	Oneof
	OneofMessage
	MapMessage
*/
package examples

import go_uber_org_zap_zapcore "go.uber.org/zap/zapcore"
import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (m *SimpleMessage) MarshalLogObject(enc go_uber_org_zap_zapcore.ObjectEncoder) error {
	enc.AddString("stringValue", m.StringValue)
	enc.AddBool("boolValue", m.BoolValue)
	return nil
}

func (m *NumberMessage) MarshalLogObject(enc go_uber_org_zap_zapcore.ObjectEncoder) error {
	enc.AddFloat32("floatValue", m.FloatValue)
	enc.AddFloat64("doubleValue", m.DoubleValue)
	enc.AddInt32("int32Value", m.Int32Value)
	enc.AddInt64("int64Value", m.Int64Value)
	enc.AddUint32("uint32Value", m.Uint32Value)
	enc.AddUint64("uint64Value", m.Uint64Value)
	enc.AddInt32("sint32Value", m.Sint32Value)
	enc.AddInt64("sint64Value", m.Sint64Value)
	enc.AddUint32("fixed32Value", m.Fixed32Value)
	enc.AddUint64("fixed64Value", m.Fixed64Value)
	enc.AddInt32("sfixed32Value", m.Sfixed32Value)
	enc.AddInt64("sfixed64Value", m.Sfixed64Value)
	return nil
}

func (m *RepeatedNumberMessage) MarshalLogObject(enc go_uber_org_zap_zapcore.ObjectEncoder) error {
	// repeated
	enc.AddArray("floatValues", go_uber_org_zap_zapcore.ArrayMarshalerFunc(func(aenc go_uber_org_zap_zapcore.ArrayEncoder) error {
		for _, v := range m.FloatValues {
			_ = v
			aenc.AppendFloat32(v)
		}
		return nil
	}))
	// repeated
	enc.AddArray("doubleValues", go_uber_org_zap_zapcore.ArrayMarshalerFunc(func(aenc go_uber_org_zap_zapcore.ArrayEncoder) error {
		for _, v := range m.DoubleValues {
			_ = v
			aenc.AppendFloat64(v)
		}
		return nil
	}))
	// repeated
	enc.AddArray("int32Values", go_uber_org_zap_zapcore.ArrayMarshalerFunc(func(aenc go_uber_org_zap_zapcore.ArrayEncoder) error {
		for _, v := range m.Int32Values {
			_ = v
			aenc.AppendInt32(v)
		}
		return nil
	}))
	// repeated
	enc.AddArray("int64Values", go_uber_org_zap_zapcore.ArrayMarshalerFunc(func(aenc go_uber_org_zap_zapcore.ArrayEncoder) error {
		for _, v := range m.Int64Values {
			_ = v
			aenc.AppendInt64(v)
		}
		return nil
	}))
	// repeated
	enc.AddArray("uint32Values", go_uber_org_zap_zapcore.ArrayMarshalerFunc(func(aenc go_uber_org_zap_zapcore.ArrayEncoder) error {
		for _, v := range m.Uint32Values {
			_ = v
			aenc.AppendUint32(v)
		}
		return nil
	}))
	// repeated
	enc.AddArray("uint64Values", go_uber_org_zap_zapcore.ArrayMarshalerFunc(func(aenc go_uber_org_zap_zapcore.ArrayEncoder) error {
		for _, v := range m.Uint64Values {
			_ = v
			aenc.AppendUint64(v)
		}
		return nil
	}))
	// repeated
	enc.AddArray("sint32Values", go_uber_org_zap_zapcore.ArrayMarshalerFunc(func(aenc go_uber_org_zap_zapcore.ArrayEncoder) error {
		for _, v := range m.Sint32Values {
			_ = v
			aenc.AppendInt32(v)
		}
		return nil
	}))
	// repeated
	enc.AddArray("sint64Values", go_uber_org_zap_zapcore.ArrayMarshalerFunc(func(aenc go_uber_org_zap_zapcore.ArrayEncoder) error {
		for _, v := range m.Sint64Values {
			_ = v
			aenc.AppendInt64(v)
		}
		return nil
	}))
	// repeated
	enc.AddArray("fixed32Values", go_uber_org_zap_zapcore.ArrayMarshalerFunc(func(aenc go_uber_org_zap_zapcore.ArrayEncoder) error {
		for _, v := range m.Fixed32Values {
			_ = v
			aenc.AppendUint32(v)
		}
		return nil
	}))
	// repeated
	enc.AddArray("fixed64Values", go_uber_org_zap_zapcore.ArrayMarshalerFunc(func(aenc go_uber_org_zap_zapcore.ArrayEncoder) error {
		for _, v := range m.Fixed64Values {
			_ = v
			aenc.AppendUint64(v)
		}
		return nil
	}))
	// repeated
	enc.AddArray("sfixed32Values", go_uber_org_zap_zapcore.ArrayMarshalerFunc(func(aenc go_uber_org_zap_zapcore.ArrayEncoder) error {
		for _, v := range m.Sfixed32Values {
			_ = v
			aenc.AppendInt32(v)
		}
		return nil
	}))
	// repeated
	enc.AddArray("sfixed64Values", go_uber_org_zap_zapcore.ArrayMarshalerFunc(func(aenc go_uber_org_zap_zapcore.ArrayEncoder) error {
		for _, v := range m.Sfixed64Values {
			_ = v
			aenc.AppendInt64(v)
		}
		return nil
	}))
	return nil
}

func (m *NestedMessage) MarshalLogObject(enc go_uber_org_zap_zapcore.ObjectEncoder) error {
	if m.NestedValue != nil {
		var vv interface{} = m.NestedValue
		if _, ok := vv.(go_uber_org_zap_zapcore.ObjectMarshaler); ok {
			enc.AddObject("nestedValue", m.NestedValue)
		}
	}
	return nil
}

func (m *NestedMessage_Nested) MarshalLogObject(enc go_uber_org_zap_zapcore.ObjectEncoder) error {
	enc.AddInt32("int32Value", m.Int32Value)
	enc.AddString("stringValue", m.StringValue)
	return nil
}

func (m *EnumMessage) MarshalLogObject(enc go_uber_org_zap_zapcore.ObjectEncoder) error {
	enc.AddString("numericEnumValue", m.NumericEnumValue.String())
	// repeated
	enc.AddArray("repeatedNumericEnumValues", go_uber_org_zap_zapcore.ArrayMarshalerFunc(func(aenc go_uber_org_zap_zapcore.ArrayEncoder) error {
		for _, v := range m.RepeatedNumericEnumValues {
			_ = v
			aenc.AppendString(v.String())
		}
		return nil
	}))
	enc.AddString("aliasedEnumValue", m.AliasedEnumValue.String())
	enc.AddString("nestedEnumValue", m.NestedEnumValue.String())
	// repeated
	enc.AddArray("repeatedNestedEnumValues", go_uber_org_zap_zapcore.ArrayMarshalerFunc(func(aenc go_uber_org_zap_zapcore.ArrayEncoder) error {
		for _, v := range m.RepeatedNestedEnumValues {
			_ = v
			aenc.AppendString(v.String())
		}
		return nil
	}))
	return nil
}

func (m *Oneof) MarshalLogObject(enc go_uber_org_zap_zapcore.ObjectEncoder) error {
	return nil
}

func (m *OneofMessage) MarshalLogObject(enc go_uber_org_zap_zapcore.ObjectEncoder) error {
	return nil
}

func (m *MapMessage) MarshalLogObject(enc go_uber_org_zap_zapcore.ObjectEncoder) error {
	return nil
}
